#' Morphological traits database
#'
#' @description
#' A reference database of morphological traits available in
#' \pkg{moRphoTaxa} for constructing standardized morphological matrices with
#' [morph_add_traits()].
#'
#' The dataset contains the qualitative and quantitative morphological
#' characters currently implemented in the package, including both broadly
#' applicable default traits and taxon-specific traits defined for selected
#' angiosperm groups.
#'
#' Each row represents a single morphological trait and provides its full
#' descriptive name, abbreviated code, trait type, and the morphological
#' preset or taxonomic group to which it belongs.
#'
#' @format A data frame with one row per morphological trait and four columns:
#'
#' \describe{
#'   \item{trait_type}{
#'     Character. Type of morphological character. Values are
#'     `"qualitative"` or `"quantitative"`.
#'   }
#'
#'   \item{trait_scope}{
#'     Character. Morphological trait set to which the character belongs.
#'     `"default"` identifies traits broadly applicable across flowering
#'     plants. Taxon-specific values identify predefined morphological
#'     presets currently implemented in \pkg{moRphoTaxa}, including
#'     `"leguminosae_pap"`, `"leguminosae_caes"`, `"passifloraceae"`,
#'     and `"asteraceae"`.
#'   }
#'
#'   \item{trait_name}{
#'     Character. Full descriptive name of the morphological trait, using
#'     standardized snake_case notation, for example `"leaf_length"` or
#'     `"corolla_color"`.
#'   }
#'
#'   \item{trait_code}{
#'     Character. Abbreviated code used by \pkg{moRphoTaxa} to identify the
#'     morphological trait, for example `"LEAFlng"` for leaf length.
#'   }
#' }
#'
#' @details
#' The database is used internally by the morphological-data workflow of
#' \pkg{moRphoTaxa} and provides a reference for the trait columns generated by
#' [morph_add_traits()].
#'
#' Traits are organized into two broad categories:
#'
#' \itemize{
#'   \item \strong{Qualitative traits}: categorical morphological characters,
#'   such as shape, color, texture, indumentum, or structural type.
#'
#'   \item \strong{Quantitative traits}: numerical morphological characters,
#'   such as length, width, area, number, diameter, or angle.
#' }
#'
#' In addition, traits are classified according to their scope. Default traits
#' represent morphological characters potentially useful across a broad range
#' of flowering plants, whereas taxon-specific traits capture morphological
#' structures particularly relevant to selected groups.
#'
#' The taxon-specific presets currently included are:
#'
#' \itemize{
#'   \item `"leguminosae_pap"`: Leguminosae, subfamily Papilionoideae;
#'   \item `"leguminosae_caes"`: Leguminosae, subfamily Caesalpinioideae;
#'   \item `"passifloraceae"`: Passifloraceae;
#'   \item `"asteraceae"`: Asteraceae.
#' }
#'
#' Users can inspect this dataset to identify available traits and their
#' corresponding codes before constructing a morphological matrix with
#' [morph_add_traits()].
#'
#' @seealso
#' [morph_add_traits()]
#'
#' @examples
#' data(traits_database)
#'
#' # Inspect the database
#' head(traits_database)
#'
#' # Available morphological trait sets
#' unique(traits_database$trait_scope)
#'
#' # Number of traits by type
#' table(traits_database$trait_type)
#'
#' # Number of traits by scope and type
#' table(
#'   traits_database$trait_scope,
#'   traits_database$trait_type
#' )
#'
#' # Retrieve all Passifloraceae traits
#' subset(
#'   traits_database,
#'   trait_scope == "passifloraceae"
#' )
#'
#' # Retrieve only quantitative default traits
#' subset(
#'   traits_database,
#'   trait_scope == "default" &
#'     trait_type == "quantitative"
#' )
#'
#' @name traits_database
#' @docType data
#' @keywords datasets
NULL
